### ISSUE TITLE
PicoAudio midi latency bug

### ISSUE THREAD

**Issue by haveyouwantto** [cagpie/PicoAudio.js#36]
Dear cagpie,

I am writing to report a bug in the PicoAudio library that I have noticed while using it to control the playback of MIDI devices. Specifically, I have noticed that there is a significant latency when performing actions such as pausing, resuming, seeking, and song switching.

As a user of the library, I have been otherwise very satisfied with its performance and have found it to be very useful in building my software. However, this latency issue is causing some problems and I would appreciate any assistance in resolving it.

Thank you for your time and consideration.

Sincerely,
haveyouwantto

**Comment by cagpie** [comment]
Thank you for your report.

When playing back with a MIDI device (using the Web MIDI API), it is intentionally delayed from the operation to stabilize playback.
https://github.com/cagpie/PicoAudio.js/blob/master/src/player/play.js#L16
(Sorry for commenting out in Japanese)

I have a fixed value for now, but it would be nice to be able to set the delay value.

**Comment by cagpie** [comment]
@haveyouwantto

add option `WebMIDIWaitTime` (Thank you @makkii-bcr !)
https://github.com/cagpie/PicoAudio.js/pull/37

Using this option should solve the problem.
Released as v1.1.2
https://www.npmjs.com/package/picoaudio/v/1.1.2

**Comment by haveyouwantto** [comment]
Thanks, that solved my problem.
