### ISSUE TITLE
`setMasterVolume`関数の引数が1.0より大きい値を受け付ける

### ISSUE THREAD

**Issue by At-sushi** [cagpie/PicoAudio.js#39]
`setMasterVolume`関数に対し、引数として2.0などの大きい数値を渡すと、マスターボリュームが1.0よりも大きくなります（マイナス値についても同様の結果でした。）

仕様かどうかわからないのでissueとさせて頂きます。

**Comment by makkii-bcr** [comment]
```setMasterVolume```は cagpie さんが最初に実装したようです。 591d7398b032f3c51ea43951f7ac09f53ff9b2a5
@cagpie これは仕様でしょうか？ 制限を入れていないだけでしょうか？

個人的には、1.0よりも値を大きくすると、音量を100%よりも大きくできるので、
さらに音量を上げるという使い方もできるかなと思ったので、1.0までの制限はなくてもいいかなと思ったりしています。
（音量上げすぎると音割れしてしまうので、ライブラリ使用者側で調整・制御が必要になってしまいますが）

マイナス値は動作確認したらプラス値と同じような動きのようですね。（厳密には波形が反転していそう？）

**Comment by cagpie** [comment]
個人的な体感ですが、他の音源での再生などと比較した際にPicoAudioで楽曲再生すると少し音量が小さめになるので、
MasterVolumeを1超えで設定することはあるとおもっています
(Picotuneでもマスターではないですが個々の楽器の音量を2倍くらいまで設定できるようにしてたりします)

マイナスの値は想定していませんでしたが、利用側でよしなに値を設定する形で制御するのが良いと思っています

どうでしょう？

(追記) どうでしょうと投げかけても答えられる人がいないので、これは仕様と断言しておきます🙏
Issue化とメンションありがとうございました🙏
